//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanmoDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RanSanDBEntities : DbContext
    {
        public RanSanDBEntities()
            : base("name=RanSanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<ProductionData> ProductionDatas { get; set; }
        public virtual DbSet<ShiftTime> ShiftTimes { get; set; }
        public virtual DbSet<DownTimeReason> DownTimeReasons { get; set; }
        public virtual DbSet<ForItem> ForItems { get; set; }
        public virtual DbSet<RejectReason> RejectReasons { get; set; }
        public virtual DbSet<ProductionReject> ProductionRejects { get; set; }
        public virtual DbSet<ProductionDownTime> ProductionDownTimes { get; set; }
        public virtual DbSet<R_Customer> R_Customer { get; set; }
        public virtual DbSet<R_Invoice> R_Invoice { get; set; }
        public virtual DbSet<R_PaidBy> R_PaidBy { get; set; }
        public virtual DbSet<R_PaymentStatus> R_PaymentStatus { get; set; }
        public virtual DbSet<R_InvoicePayment> R_InvoicePayment { get; set; }
        public virtual DbSet<R_Payments> R_Payments { get; set; }
    }
}
