//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanmoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> FullShotWeight { get; set; }
        public Nullable<decimal> WithoutRunnerWeight { get; set; }
        public Nullable<decimal> CycleTime { get; set; }
        public Nullable<decimal> PerHourTarget { get; set; }
        public bool IsActive { get; set; }
        public string ItemFor { get; set; }
    }
}
