//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanmoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Customer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
