//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanmoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Invoice
    {
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public bool FullyPaid { get; set; }
        public string Notes { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    }
}
