//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanmoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Payments
    {
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PaidById { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNum { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<decimal> AmountRemaining { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ReceiptNo { get; set; }
        public int CustomerId { get; set; }
    }
}
